### ISSUE TITLE
An, um... installation guide within the readme?

### ISSUE THREAD

**Issue by lolnothecomplainer** [ShadowTheHedgehogHacking/ShdTH-Reloaded#1]
Sounds weird, I know, but wouldn't it technically be a feature request in a way?

**Comment by dreamsyntax** [comment]
This is currently not in a release state. Closer to release there will be an actual setup guide.

That said if you want to test it as is all you have to do is replace game files and use the provided gecko codes (GUPE8P.ini in the repo).
Recommended you extract the game in FST format for Dolphin, see this readme below on the section for FST format Extraction

https://github.com/ShadowTheHedgehogHacking/2P-ShdTH/blob/master/workspace/README.md

**Comment by lolnothecomplainer** [comment]
Good to know: if progress is still being made to the mod, then I'll gladly excuse the lack of a definitive guide to installing it.
