### ISSUE TITLE
re

### ISSUE THREAD

**Issue by bruhicantthinkofauser** [ShadowTheHedgehogHacking/ShdTH-Reloaded#12]
The sound in my game is glitching hard how do you fix this?

**Comment by dreamsyntax** [comment]
If its just generally sounding bad all the time my guess is the CPU Clock override is too high for that device you are using.

Open Dolphin -> Config -> Advanced and change the CPU Clock Override to less (try 100% if the original game runs fine for you)
You have to do this **while the game is already running**

**Comment by dreamsyntax** [comment]
Confirmed this is due to user's specs
