### ISSUE TITLE
Cannot patch ISO

### ISSUE THREAD

**Issue by Blastinburn** [ShadowTheHedgehogHacking/ShdTH-Reloaded#16]
Whenever I attempt to patch the ISO I get an error that the patcher cannot find the vcdiff file and it moves my ISO to the old folder without creating a patched ISO.  I've confirmed I have the same md5 checksum from the "how to setup" video.
fc936c9b0144c925b45b805fd39da2ac

![image](https://github.com/ShadowTheHedgehogHacking/ShdTH-Reloaded/assets/81775104/172f369f-c4d7-4513-b6e9-3c6e94f426e7)

![image](https://github.com/ShadowTheHedgehogHacking/ShdTH-Reloaded/assets/81775104/0fb11a04-3666-4521-8bc3-9a799af0aa89)

I'm using the 1.1 widescreen version.

**Comment by dreamsyntax** [comment]
Hi, this old patcher may have some issues on some systems. Instead use this webasm patcher:

https://shadowthehedgehoghacking.github.io/xdelta-wasm/ or https://kotcrab.github.io/xdelta-wasm/

Select the files like so:

Source file:
`GUPE8P.iso`
Patch file:
`GUPE8P.iso.vcdiff` - You can find this in the v1.1 folder's `vcdiff` subfolder 

It will then 'download' the patched file as GUPE8P-patched.iso (nothing is actually uploaded/downloaded, its through wasm on-device patching):

![image](https://github.com/ShadowTheHedgehogHacking/ShdTH-Reloaded/assets/14857235/47f1cf54-4184-45a2-b092-3ffff70e8860)


You can then rename this ISO as you like and it should work as expected.

**Comment by Blastinburn** [comment]
Thank you, that patcher worked.
