### ISSUE TITLE
Melee attack won't work

### ISSUE THREAD

**Issue by Robo-man123** [ShadowTheHedgehogHacking/ShdTH-Reloaded#18]
Shadow don't swing his weapon. I tried to disable "No Ammo for Melee Weapons", but it won't help.

**Comment by dreamsyntax** [comment]
Read instruction (Z to mode switch, or B+L for new mode)

Otherwise 1.2 defaults to original and Z to mode switch to new melee.

**Comment by Robo-man123** [comment]
Oh, yeah... Sorry for ignorance
