### ISSUE TITLE
No UI in Levels

### ISSUE THREAD

**Issue by Grip555** [ShadowTheHedgehogHacking/ShdTH-Reloaded#19]
I downloaded the widescreen version of the NTSC patch and none of the UI appears at all in the stages. I can't even get the pause menu icons to show up.

**Comment by dreamsyntax** [comment]
Hi, provide info.
Version of dolphin, did you have cheats enabled, did you have freecam on, etc
What hashes are in the Verify tab in Dolphin?

**Comment by Grip555** [comment]
I worked it out. It was due to the playable cutscenes mod.
