### ISSUE TITLE
How complete is this project so far? And how does one download/set it up?

### ISSUE THREAD

**Issue by Escavalien** [ShadowTheHedgehogHacking/ShdTH-Reloaded#2]
Title. This seems like the only active STH mod that's trying to fix the core issues of the game.

**Comment by LimblessVector** [comment]
Everything under the "Less Tedious Gameplay" and "Misc. QoL Changes" sections of the readme are mostly complete, while the "Genuine Challenge" and "Refreshed Art" sections are still very WIP. Unfortunately I don't have as much time these days to work on this project as I used to.

If you already know how to use Dolphin, then getting Reloaded to work isn't too hard. Download a [recent beta build](https://dolphin-emu.org/download/), and [extract your NTSC .iso of Shadow the Hedgehog into a folder](https://cdn.discordapp.com/attachments/288415776782942210/745134148028465212/unknown.png). Copy and overwrite this git's "files" folder over the one in your extracted game folder. Grab the GUPE8P.ini file in this git's "code" folder and place it in your Documents/Dolphin Emulator/GameSettings folder. Then you can customize what codes get applied by right-clicking the game in the game list >Properties > Gecko Codes.

**Comment by Escavalien** [comment]
> 
> 
> Everything under the "Less Tedious Gameplay" and "Misc. QoL Changes" sections of the readme are mostly complete, while the "Genuine Challenge" and "Refreshed Art" sections are still very WIP. Unfortunately I don't have as much time these days to work on this project as I used to.
> 
> If you already know how to use Dolphin, then getting Reloaded to work isn't too hard. Download a [recent beta build](https://dolphin-emu.org/download/), and [extract your NTSC .iso of Shadow the Hedgehog into a folder](https://cdn.discordapp.com/attachments/288415776782942210/745134148028465212/unknown.png). Copy and overwrite this git's "files" folder over the one in your extracted game folder. Grab the GUPE8P.ini file in this git's "code" folder and place it in your Documents/Dolphin Emulator/GameSettings folder. Then you can customize what codes get applied by right-clicking the game in the game list >Properties > Gecko Codes.

Thanks for the reply. I wanted to ask what features exactly from QoL and Gameplay changes are done so far? Which are missing?

**Comment by LimblessVector** [comment]
For the Gameplay section, only the "slow elevators" and "adjustments to layouts" aren't entirely complete for every stage, but the most obvious offenders are fixed (probably). 

Everything in QoL is actually done, but there's been more that's been added since writing that page, which can be read in the Gecko cheats settings. Some examples are the Bloom Reduction, Manual Mission Override, and "Death Counter System" codes.

**Comment by Escavalien** [comment]
> 
> 
> For the Gameplay section, only the "slow elevators" and "adjustments to layouts" aren't entirely complete for every stage, but the most obvious offenders are fixed (probably).
> 
> Everything in QoL is actually done, but there's been more that's been added since writing that page, which can be read in the Gecko cheats settings. Some examples are the Bloom Reduction, Manual Mission Override, and "Death Counter System" codes.

So by the looks of it with this STH will actually be tolerable to go through and finish. Thanks for all of your hard work, it'll make this game a lot more fun for me and my friends.

**Comment by Escavalien** [comment]
I finally got around to playing and I've noticed that everything works fine but some things made me scratch my head in confusion. Isn't one of the improvements reducing big objective numbers? I haven't noticed any changes for the hero route so far. Did you decide to only change missions that were notorious like the one with Maria? But aren't most of the game's missions too tedious in the first place? I would say practically every mission could make use out of a much lower objective count wouldn't it?

**Comment by dreamsyntax** [comment]
As Limbless said its barely been touched. Focus was on other changes first. Legacy 2018 version had more layout related changes but Limbless started from scratch with the better tools we now have.

We've been busy with other things.

The only level that could could be considered 'complete' is Digital Circuit
