### ISSUE TITLE
Game crashes on first level

### ISSUE THREAD

**Issue by floweywastaken** [ShadowTheHedgehogHacking/ShdTH-Reloaded#20]
Game crashes when you open first level on latest nintendont unlocked read speed and memcard emulation on wii will respond to any questions

**Comment by dreamsyntax** [comment]
Follow the readme, requires custom nintendont build until they merge in the oversized ISO patch.

**Comment by floweywastaken** [comment]
> Follow the readme, requires custom nintendont build until they merge in the oversized ISO patch.

I need to know since i cant find it due to inly seeing normal nintendont does it let me play other games cause i might need to delete normal nintendont to see it

**Comment by floweywastaken** [comment]
Nevermind it was a faulty transfer imm gonna try it and see if it works

**Comment by floweywastaken** [comment]
I fixed it i got the custom nintendont loader and i incorrectly downloaded it first time
