### ISSUE TITLE
Is it possible to manually change some of the mission requirements?

### ISSUE THREAD

**Issue by ColossusSteppes** [ShadowTheHedgehogHacking/ShdTH-Reloaded#21]
While having reduced requirements for levels The Doom Dark or Lost Impact Hero are nice, others such as reducing the amount of big bombs in Central City or the amound of generators in Lava Shelter don't really seem necessary.

I know you're not planning on updating this anymore, so is there a way for us to manually adjust these requirements for certain levels while keeping all of Reloaded's other features?

**Comment by dreamsyntax** [comment]
We don't change the generators in lava shelter, or the big bombs in central city.
You should have '5' big bombs in Central City, '20' small; and 5 generators in Lava Shelter.

You likely installed the 'reduced missions' mod which conflicts with Reloaded, as it is intended for the base game.

> ... is there a way for us to manually adjust these requirements for certain levels...

Yes, missions are in plain-text in the nukkoro2.inf file. Edit it with notepad/notepad++ etc in your extracted game.

Our inf also has the stage names commented and the `#Reloaded 1.2 Ranks` block at the top. If it is missing that further confirms you installed something that overrode missions.

https://github.com/ShadowTheHedgehogHacking/ShdTH-Reloaded/blob/master/ISO%20EDITS/files/nukkoro2.inf

**Comment by ColossusSteppes** [comment]
Ah sorry, I guess I should've looked into this myself before asking. I was [watching a playthrough](https://youtu.be/FEN0hfOwpzY?t=6359) which seems to have that installed. I've been going for 326 on the original so I haven't really tried much of Reloaded outside of expert mode.

But thanks for the info regarding changing it!

**Comment by ColossusSteppes** [comment]
One small thing that isn't worth creating a new issue for

![image](https://github.com/user-attachments/assets/d9de841f-7795-4896-872b-77e8276b3351)

I see that the scores required for an S rank in Mad Matrix Dark is pretty high, but if I wanted to change the Reloaded requirements from 20 to 25 bombs, would bumping the S Rank requirement down to 25000 seem like a fair score to balance out taking more time to get the extra bombs?
This isn't anything important, so no worries if you don't remember the exact calculations for S ranks!
