### ISSUE TITLE
Incorrect Aspect Ratio

### ISSUE THREAD

**Issue by ColossusSteppes** [ShadowTheHedgehogHacking/ShdTH-Reloaded#22]
Based on the [release video](https://www.youtube.com/watch?v=1yM2kJjyhZQ), Reloaded Widescreen seems to be in 16:9, but for some reason mine is a different aspect ratio. Instead of 2560x1440, it's 2334x1440

![ShadowAspect](https://github.com/user-attachments/assets/fd8c8305-4dbd-481c-96fd-01d672f0d443)

This happens when the aspect ratio in Dolphin is set to Auto or Forced 16:9.
Setting it to Stretch to Window makes it 16:9 (but obviously stretched), so it doesn't seem like there's any sort of "fake" black border on each side.

It's still great to have it this wide compared to the original, but any help would be appreciated!

**Comment by dreamsyntax** [comment]
Hi, this is normal for Sonic Heroes and Shadow the Hedgehog. I forget the technical explanation, but tldr use Crop under Advanced or Stretch to Window. It is related to how the game's internal resolution works. Similarly on real hardware on Nintendont you would need to use 714 width as a workaround for the bars.

On a 16:10 display the Auto/16:9 would look as you are expecting but with a few px on the bottom.

**Comment by ColossusSteppes** [comment]
Thanks for the reply!
Just to check, does this mean that the view I have currently is squished, and setting it to "stretch" will make it normal? Or is the current view normal and setting it to stretch will stretch the image?

I'd rather have the bars at the side than a stretched image.

**Comment by dreamsyntax** [comment]
1. Stretch will slightly stretch (its not a huge amount)

2. 16:9 will have black bars on 16:9 displays

3. 16:9 with Crop will not stretch but will be slightly zoomed in

I advise trying all to see what looks best for you. I usually do option 2 or 3

**Comment by ColossusSteppes** [comment]
Thank you!
