### ISSUE TITLE
MCM Stuff

### ISSUE THREAD

**Issue by Fivavoa** [ShadowTheHedgehogHacking/ShdTH-Reloaded#5]
Hey! Been messing around with this these past few days (red ring placements are brutal), very good work!

Just a question, it's been a while but I tried to update it recently and there's this python thing for the code now? How would you go about installing this? I tried looking through the readme on this page and I can't see mention on where and how this is integrated.

**Comment by dreamsyntax** [comment]
Tentative release date is 10/10/2022, so this is already very close to final.
Instructions etc will be updated then.

As an end user you don't have to touch anything MCM related.


The ISO EDITS contains the \sys folder which already has the latest patched DOL.
We are still in progress converting remaining gecko to MCM.
Then gecko would be entirely optional for cheats only and widescreen

We are looking into issues with the current AFS changes so please hold off on using PAFS for patching the AFS edits
Nintendont compatibility also breaks if you include the .flo files at the moment

We have a temporary feedback server here that will be up for a brief period if you have any feedback
https://discord.gg/kscv3upbsG
